name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "18.17.0"  # Update to the required version
        cache: ${{ steps.detect-package-manager.outputs.manager }}

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out # Mettez à jour avec le répertoire de build de votre projet

    - name: Cleanup
      run: rm -rf out # Supprimez le répertoire de build après le déploiement
